### PR TITLE
Registration Check confirm password fucntion

### PR DESCRIPTION
**Pull request by pakkaponvstw**

### CODE REVIEW

**Comment by patdpat** [comment]
Everything is working fine, but as you go through this process in our next iteration, you should completely test the system by walking through the same process as your users.
Great Job!
PS I'll wait until others test and comment, then I'll merge and resolve conflicted files myself.

**Comment by mmookptr** [comment]
As I tested, the function works just fine. Well done!

**Comment by patdpat** [comment]
Gret work

**Comment by patdpat** [comment]
Great Job!

**Pull request merged**
