### PR TITLE
Loginpagestyling

### PR DESCRIPTION
**Pull request by mmookptr**
I've edited login page styling, please checkout branch 'loginpagestyling' and let me know if anything needs to be changed or edited.

### CODE REVIEW

**Comment by patdpat** [comment]
Everything is working pretty well after all of us has reviewed I'll merge it to the master branch myself.

**Comment by mark47546** [comment]
Everything is working well. Well done.

**Comment by pakkaponvstw** [comment]
Your work is work pretty well. Good work.

**Comment by patdpat** [comment]
Merge approve 4/4

**Pull request merged**
