### PR TITLE
Add Facebook SocialAuthentication

### PR DESCRIPTION
**Pull request by mark47546**

### CODE REVIEW

**Comment by pakkaponvstw** [comment]
Your code work pretty well, Nicely done.

**Comment by mmookptr** [comment]
I've found some misspelling and comments, please check for spelling errors and delete those comments from your file. I'll test everything again after.

**Comment by mark47546** [comment]
> .



> I've found some misspelling and comments, please check for spelling errors and delete those comments from your file. I'll test everything again after.

**Comment by mark47546** [comment]
> I've found some misspelling and comments, please check for spelling errors and delete those comments from your file. I'll test everything again after.

I've deleted the comments and correct the spelling errors. Please test it again and let me know if there's any further issue. Many thanks!

**Comment by patdpat** [comment]
Seems. fine

**Pull request merged**
